### ISSUE TITLE
License

### ISSUE THREAD

**Issue by aymanhab** [mitkof6/OpenSimRT#19]
Any reason to use GPL license as opposed to OpenSim style license (MIT, BSD etc.)? This may be a problem if we decide to integrate bits and pieces into OpenSim.

**Comment by mitkof6** [comment]
Hi Ayman,

We wanted to avoid situations where the derivatives of this work become closed source and to increase the chances of people contributing back. However, we are open to discuss alternatives or granting OpenSim to use or adapt any part of the code.
