### ISSUE TITLE
Unable to compile TestAccelerationGRFMPredictionFromFIle.cpp

### ISSUE THREAD

**Issue by Kristofferson777** [mitkof6/OpenSimRT#24]
When building TestAccelerationGRFMPredictionFromFIle.cpp in visual studio code I am getting a cmake error which is as followsL:

[cmake] CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
[cmake] Please set them or make sure they are set and tested correctly in the CMake files:
[cmake] oscpack
[cmake]     linked by target "IMU" in directory C:/Users/Chris/OneDrive/Desktop/OpenSimRT-master/OpenSimRT/IMU
[cmake]     linked by target "TestLowerLimbIMUIKFromFile" in directory C:/Users/Chris/OneDrive/Desktop/OpenSimRT-master/OpenSimRT/IMU
[cmake]     linked by target "TestUpperLimbIMUIKFromFile" in directory C:/Users/Chris/OneDrive/Desktop/OpenSimRT-master/OpenSimRT/IMU
[cmake]     linked by target "OnlineLowerLimbIMUIK" in directory C:/Users/Chris/OneDrive/Desktop/OpenSimRT-master/OpenSimRT/IMU
[cmake]     linked by target "OnlineUpperLimbIMUIK" in directory C:/Users/Chris/OneDrive/Desktop/OpenSimRT-master/OpenSimRT/IMU
[cmake] 
[cmake] -- Generating done
[cmake] CMake Generate step failed.  Build files cannot be regenerated correctly.

Not sure what to do from here

**Comment by mitkof6** [comment]
Not related to a bug/issue of the project.
